[changelog]
header = """
# Changelog

"""
body = """
{% if version %}\
    ## {{ version | trim_start_matches(pat="v") }}

{% else %}\
    ## Unreleased

{% endif %}\
{% for group, commits in commits | filter(attribute="group", value="Features") | group_by(attribute="group") %}\
    ### {{ group | upper_first }}
    {% for commit in commits %}
        - {{ commit.message | upper_first }}\
    {% endfor %}\n
{% endfor %}\
{% for group, commits in commits | filter(attribute="group", value="Fixes") | group_by(attribute="group") %}\
    ### {{ group | upper_first }}
    {% for commit in commits %}
        - {{ commit.message | upper_first }}\
    {% endfor %}\n
{% endfor %}\
"""
trim = true

[git]
conventional_commits = true
filter_unconventional = true
commit_parsers = [
  { message = "^feat", group = "Features" },
  { message = "^fix", group = "Fixes" },
  { message = "^docs", group = "Documentation", skip = true },
]
# filter_commits = true
